version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock  # Volumen para comunicarse con Docker
      - portainer_data:/data  # Volumen para almacenar los datos de Portainer

volumes:
  portainer_data:
