services:
  mongodb:
    image: mongo:5.0.9-focal
    container_name: mongodb_contenedor
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017
    volumes:
      - ./usuarios.json:/data/usuarios.json
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
