version: "3"
services:
  portainer_service:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: